name: Tests

on:
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - dev
            - main
    push:
        branches:
            - dev
            - main
jobs:
    run-tests:
        name: All tests
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        env:
            BROWSER: chrome
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 18.18.0
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: All tests
              run: npm run test
            - name: Upload coverage
              uses: codecov/codecov-action@v5
              with:
                  fail_ci_if_error: false
                  codecov_yml_path: ./.github/codecov.yml
                  token: ${{ secrets.CODECOV_TOKEN }}
    test-code-examples:
        name: Check typedocs
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:31739588
                  node-version: 18.18.0
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Build Docs
              run: npm run build && npm run docs:json
            - name: tsdoc @example checks
              run: npm run test:examples
    test-html-examples:
        name: Run HTML Examples
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 18.18.0
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Code example tests
              run: npm run test:html
    test-lint:
        name: Linting and environment checks
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 18.18.0
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Linting
              run: npm run lint
    test-readme:
        name: Ensure that examples in the README compile
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 18.18.0
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test:readme
    test-integrations:
        name: Test integrations
        permissions:
            contents: read
            id-token: write
        runs-on: ubuntu-latest
        steps:
            - name: Check out Git repository
              uses: actions/checkout@v4
            - name: Setup Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 18.18.0
                  cache: "npm"
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Test
              run: npm run test:integrations
    publish:
        runs-on: ubuntu-latest
        # make sure all the tests pass first
        needs:
            [
                run-tests,
                test-code-examples,
                test-html-examples,
                test-lint,
                test-readme,
                test-integrations,
            ]
        # not on PRs
        if: github.event_name != 'pull_request'
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            GITHUB_CI: true
        steps:
            - uses: actions/checkout@v4
            # Setup .npmrc file to publish to npm
            - uses: actions/setup-node@v4
              with:
                  node-version: 18.18.0
                  registry-url: "https://registry.npmjs.org"
            - name: Install dependencies
              run: npm install
            - name: Build
              run: npm run build
            - name: Increment version
              run: npm run increment
            - name: Publish @next
              # dev branch gets published with @next tag
              run: npm publish --tag next
              if: ${{ github.ref == 'refs/heads/dev' }}
            - name: Publish @latest
              # main branch gets published with @latest tag
              run: npm publish
              if: ${{ github.ref == 'refs/heads/main' }}
            - name: Setup Node.js environment
  uses: actions/setup-node@v3.9.1
  with:
    # Set always-auth in npmrc.
    always-auth: # optional, default is false
    # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
    node-version: # optional
    # File containing the version Spec of the version to use.  Examples: .nvmrc, .node-version, .tool-versions.
    node-version-file: # optional
    # Target architecture for Node to use. Examples: x86, x64. Will use system architecture by default.
    architecture: # optional
    # Set this option if you want the action to check for the latest available version that satisfies the version spec.
    check-latest: # optional
    # Optional registry to set up for auth. Will set the registry in a project level .npmrc and .yarnrc file, and set up auth to read in from env.NODE_AUTH_TOKEN.
    registry-url: # optional
    # Optional scope for authenticating against scoped registries. Will fall back to the repository owner when using the GitHub Packages registry (https://npm.pkg.github.com/).
    scope: # optional
    # Used to pull node distributions from node-versions. Since there's a default, this is typically not supplied by the user. When running this action on github.com, the default value is sufficient. When running on GHES, you can pass a personal access token for github.com if you are experiencing rate limiting.
    token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
    cache: # optional
    # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
    cache-dependency-path: # optional
          
